RPM Signing feature compatibility updates for the new RPM 4.16.1.3 and new GPG 2.3.3.
Only attempt to sign if "--sign-setup" has been run or if a "%_signature" macro exists.

Port RPM signing process from "rpmbuild" to "rpmsign" to prevent this crashing spewage:

error: rpmbuild --sign is no longer supported. Use the rpmsign command instead!

Use "--with-colons" for more machine parsable output to avoid
problems from variations in the "gpg --list-keys" output,
which may keep breaking in the future due to more tweaks in the output.