fix sanitization of simple spec file fields
For this command:

    ./cpan2rpm --no-sign https://cpan.metacpan.org/authors/id/G/GS/GSHANK/Crypt-SaltedHash-0.09.tar.gz

There is a fatal error:

    error: line 16: Unknown tag: with salted hashes.

The error is a result of the abstract line in the source metadata:

    "abstract" : "Perl interface to functions that assist in working\r\nwith salted hashes.\r",

Currently, cpan2rpm generates a spec file with:

    summary:   Crypt-SaltedHash - Perl interface to functions that assist in working^M
    with salted hashes.^M

To fix this, we need two changes:

1. When stripping carriage returns, loop over $info->{'opts-simple'},
   not the global %info, which does not necessarily contain keys for
   generated data such as 'summary'.
2. For these fields, also translate newlines to spaces.